### ISSUE TITLE
Failed to connect to ST-2000XCM

### ISSUE THREAD

**Issue by chasmiller46** [cedric-r/ASCOM.HomeMade.SBIGCamera#3]
I am an ASCOM developer and I installed your SBIG ASCOM driver and attempted to connect to my ST-2000XCM in my imaging application.  The connection failed.  I can see in Device Manager that the camera's USB interface is flagged as Unknown.

Do I need to download any DLL files from SBIG?  I only ran your Setup program.

SBIG_Common_xxxx.log:
10/9/2021 13:14:21.452: Connect: Connection request
10/9/2021 13:14:21.458: Connected Set: Enumerating USB cameras
10/9/2021 13:14:21.458: Connected Set: No camera found
10/9/2021 13:14:21.458: Disconnect: Disconnecting device
10/9/2021 13:14:21.475: SBIGService HandleMessage: Message is CCD_INFO
10/9/2021 13:14:21.481: SBIGService HandleMessage: Error: CE_DRIVER_NOT_OPEN
   at SbigSharp.SBIG.UnivDrvCommand[TParams,TResults](PAR_COMMAND command, TParams Params, TResults& pResults)
   at ASCOM.HomeMade.SBIGCommon.SBIGHandler.UnivDrvCommand[TParams,TResults](PAR_COMMAND command, TParams Params, TResults& pResults)
   at ASCOM.HomeMade.SBIGCommon.SBIGHandler.HandleMessage(SBIGRequest request)

10/9/2021 13:14:21.490: Disconnect: Disconnection requested
10/9/2021 13:14:21.490: Disconnect: Disconnecting device

SBIG_Imaging_Camera_xxxx.log
10/9/2021 13:14:21.427: Camera: Starting initialisation
10/9/2021 13:14:21.427: DriverVersion Get: 1.1.0
ASCOM.HomeMade.SBIGImagingCamera v1.1.0
Process ID: 12744
10/9/2021 13:14:21.427: Camera: Completed initialisation
10/9/2021 13:14:21.443: InterfaceVersion Get: 3
10/9/2021 13:14:21.445: Connected: Set True
10/9/2021 13:14:21.447: IsConnected: connectionState=False
10/9/2021 13:14:21.458: Connected Set: Connected to camera
10/9/2021 13:14:21.458: Connected Set: Getting camera info
10/9/2021 13:14:21.458: IsConnected: connectionState=True
10/9/2021 13:14:21.484: Connected Set: Error: CE_DRIVER_NOT_OPEN
   at ASCOM.HomeMade.SBIGClient.SBIGClient.CCD_INFO(GetCCDInfoParams tparams)
   at ASCOM.HomeMade.SBIGClient.ISBIGCameraSpecs.GetCameraSpecs()

10/9/2021 13:14:21.486: Connected Set: Error: CE_DRIVER_NOT_OPEN
   at ASCOM.HomeMade.SBIGClient.SBIGClient.CCD_INFO(GetCCDInfoParams tparams)
   at ASCOM.HomeMade.SBIGClient.ISBIGCameraSpecs.GetCameraSpecs()

   at ASCOM.HomeMade.SBIGClient.ISBIGCameraSpecs.GetCameraSpecs()
   at ASCOM.HomeMade.SBIGCamera.SBIGCamera.set_Connected(Boolean value)

10/9/2021 13:14:21.490: IsConnected: connectionState=True

Charlie Miller
chasmiller46@gmail.com

**Comment by cedric-r** [comment]
Hello,

No you don't need to download anything else. It looks like the SBIG library didn't find any SBIG usb cameras. That part is out of the driver's control.

Did you install a single version of the driver? Or was it an update? Did you check the camera connection with the SBIG utilities? Just to be sure.

I think the driver had been tested with an ST-2000 before, but I'm not certain as I don't have one.

Thanks.
